# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: match_ticket_mobile.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# import error_pb2 as error__pb2
# import common_mobile_pb2 as common__mobile__pb2
# import match_mobile_pb2 as match__mobile__pb2

from Celer_Game.celer_games_api_regression.pythonLib.Celer_match_ticket_mobile import error__pb2
from Celer_Game.celer_games_api_regression.pythonLib.Celer_match_ticket_mobile import \
  common_mobile_pb2 as common__mobile__pb2
from Celer_Game.celer_games_api_regression.pythonLib.Celer_match_ticket_mobile import match_mobile_pb2 as match__mobile__pb2



DESCRIPTOR = _descriptor.FileDescriptor(
  name='match_ticket_mobile.proto',
  package='ticket',
  syntax='proto3',
  serialized_options=b'\n\032network.celer.proto.ticketB\021MatchTicketMobile\272\002\013MatchTicket',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19match_ticket_mobile.proto\x12\x06ticket\x1a\x0b\x65rror.proto\x1a\x13\x63ommon_mobile.proto\x1a\x12match_mobile.proto\"r\n\x1fGetMatchDetailByTicketIdRequest\x12\x11\n\tticket_id\x18\x01 \x01(\t\x12\x13\n\x0b\x61pp_version\x18\x02 \x01(\t\x12\'\n\x0b\x64\x65vice_type\x18\x03 \x01(\x0e\x32\x12.common.DeviceType\"U\n\x1cRefundWhenGameCrashedRequest\x12\x11\n\tticket_id\x18\x01 \x01(\x03\x12\r\n\x05token\x18\x02 \x01(\t\x12\x13\n\x0bsubmit_time\x18\x03 \x01(\x04\"v\n\x1dRefundWhenGameCrashedResponse\x12 \n\x05\x65rror\x18\x01 \x01(\x0b\x32\x11.err.BackendError\x12\x33\n\rrefund_result\x18\x02 \x01(\x0e\x32\x1c.ticket.AutoRefundResultEnum\"w\n GetMatchDetailByTicketIdResponse\x12 \n\x05\x65rror\x18\x01 \x01(\x0b\x32\x11.err.BackendError\x12\x31\n\x11match_detail_info\x18\x02 \x01(\x0b\x32\x16.match.MatchDetailInfo*\x84\x01\n\x14\x41utoRefundResultEnum\x12 \n\x1c\x41UTO_REFUND_RESULT_UNDEFINED\x10\x00\x12\x1e\n\x1a\x41UTO_REFUND_RESULT_SUCCESS\x10\x01\x12*\n&AUTO_REFUND_RESULT_WRONG_TICKET_STATUS\x10\x02\x32\xe1\x01\n\x06Mobile\x12\x66\n\x15RefundWhenGameCrashed\x12$.ticket.RefundWhenGameCrashedRequest\x1a%.ticket.RefundWhenGameCrashedResponse\"\x00\x12o\n\x18GetMatchDetailByTicketId\x12\'.ticket.GetMatchDetailByTicketIdRequest\x1a(.ticket.GetMatchDetailByTicketIdResponse\"\x00\x42=\n\x1anetwork.celer.proto.ticketB\x11MatchTicketMobile\xba\x02\x0bMatchTicketb\x06proto3'
  ,
  dependencies=[error__pb2.DESCRIPTOR,common__mobile__pb2.DESCRIPTOR,match__mobile__pb2.DESCRIPTOR,])

_AUTOREFUNDRESULTENUM = _descriptor.EnumDescriptor(
  name='AutoRefundResultEnum',
  full_name='ticket.AutoRefundResultEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AUTO_REFUND_RESULT_UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUTO_REFUND_RESULT_SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUTO_REFUND_RESULT_WRONG_TICKET_STATUS', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=536,
  serialized_end=668,
)
_sym_db.RegisterEnumDescriptor(_AUTOREFUNDRESULTENUM)

AutoRefundResultEnum = enum_type_wrapper.EnumTypeWrapper(_AUTOREFUNDRESULTENUM)
AUTO_REFUND_RESULT_UNDEFINED = 0
AUTO_REFUND_RESULT_SUCCESS = 1
AUTO_REFUND_RESULT_WRONG_TICKET_STATUS = 2



_GETMATCHDETAILBYTICKETIDREQUEST = _descriptor.Descriptor(
  name='GetMatchDetailByTicketIdRequest',
  full_name='ticket.GetMatchDetailByTicketIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket_id', full_name='ticket.GetMatchDetailByTicketIdRequest.ticket_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='app_version', full_name='ticket.GetMatchDetailByTicketIdRequest.app_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_type', full_name='ticket.GetMatchDetailByTicketIdRequest.device_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=205,
)


_REFUNDWHENGAMECRASHEDREQUEST = _descriptor.Descriptor(
  name='RefundWhenGameCrashedRequest',
  full_name='ticket.RefundWhenGameCrashedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket_id', full_name='ticket.RefundWhenGameCrashedRequest.ticket_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='ticket.RefundWhenGameCrashedRequest.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='submit_time', full_name='ticket.RefundWhenGameCrashedRequest.submit_time', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=292,
)


_REFUNDWHENGAMECRASHEDRESPONSE = _descriptor.Descriptor(
  name='RefundWhenGameCrashedResponse',
  full_name='ticket.RefundWhenGameCrashedResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='ticket.RefundWhenGameCrashedResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='refund_result', full_name='ticket.RefundWhenGameCrashedResponse.refund_result', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=412,
)


_GETMATCHDETAILBYTICKETIDRESPONSE = _descriptor.Descriptor(
  name='GetMatchDetailByTicketIdResponse',
  full_name='ticket.GetMatchDetailByTicketIdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='ticket.GetMatchDetailByTicketIdResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='match_detail_info', full_name='ticket.GetMatchDetailByTicketIdResponse.match_detail_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=533,
)

_GETMATCHDETAILBYTICKETIDREQUEST.fields_by_name['device_type'].enum_type = common__mobile__pb2._DEVICETYPE
_REFUNDWHENGAMECRASHEDRESPONSE.fields_by_name['error'].message_type = error__pb2._BACKENDERROR
_REFUNDWHENGAMECRASHEDRESPONSE.fields_by_name['refund_result'].enum_type = _AUTOREFUNDRESULTENUM
_GETMATCHDETAILBYTICKETIDRESPONSE.fields_by_name['error'].message_type = error__pb2._BACKENDERROR
_GETMATCHDETAILBYTICKETIDRESPONSE.fields_by_name['match_detail_info'].message_type = match__mobile__pb2._MATCHDETAILINFO
DESCRIPTOR.message_types_by_name['GetMatchDetailByTicketIdRequest'] = _GETMATCHDETAILBYTICKETIDREQUEST
DESCRIPTOR.message_types_by_name['RefundWhenGameCrashedRequest'] = _REFUNDWHENGAMECRASHEDREQUEST
DESCRIPTOR.message_types_by_name['RefundWhenGameCrashedResponse'] = _REFUNDWHENGAMECRASHEDRESPONSE
DESCRIPTOR.message_types_by_name['GetMatchDetailByTicketIdResponse'] = _GETMATCHDETAILBYTICKETIDRESPONSE
DESCRIPTOR.enum_types_by_name['AutoRefundResultEnum'] = _AUTOREFUNDRESULTENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetMatchDetailByTicketIdRequest = _reflection.GeneratedProtocolMessageType('GetMatchDetailByTicketIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMATCHDETAILBYTICKETIDREQUEST,
  '__module__' : 'match_ticket_mobile_pb2'
  # @@protoc_insertion_point(class_scope:ticket.GetMatchDetailByTicketIdRequest)
  })
_sym_db.RegisterMessage(GetMatchDetailByTicketIdRequest)

RefundWhenGameCrashedRequest = _reflection.GeneratedProtocolMessageType('RefundWhenGameCrashedRequest', (_message.Message,), {
  'DESCRIPTOR' : _REFUNDWHENGAMECRASHEDREQUEST,
  '__module__' : 'match_ticket_mobile_pb2'
  # @@protoc_insertion_point(class_scope:ticket.RefundWhenGameCrashedRequest)
  })
_sym_db.RegisterMessage(RefundWhenGameCrashedRequest)

RefundWhenGameCrashedResponse = _reflection.GeneratedProtocolMessageType('RefundWhenGameCrashedResponse', (_message.Message,), {
  'DESCRIPTOR' : _REFUNDWHENGAMECRASHEDRESPONSE,
  '__module__' : 'match_ticket_mobile_pb2'
  # @@protoc_insertion_point(class_scope:ticket.RefundWhenGameCrashedResponse)
  })
_sym_db.RegisterMessage(RefundWhenGameCrashedResponse)

GetMatchDetailByTicketIdResponse = _reflection.GeneratedProtocolMessageType('GetMatchDetailByTicketIdResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETMATCHDETAILBYTICKETIDRESPONSE,
  '__module__' : 'match_ticket_mobile_pb2'
  # @@protoc_insertion_point(class_scope:ticket.GetMatchDetailByTicketIdResponse)
  })
_sym_db.RegisterMessage(GetMatchDetailByTicketIdResponse)


DESCRIPTOR._options = None

_MOBILE = _descriptor.ServiceDescriptor(
  name='Mobile',
  full_name='ticket.Mobile',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=671,
  serialized_end=896,
  methods=[
  _descriptor.MethodDescriptor(
    name='RefundWhenGameCrashed',
    full_name='ticket.Mobile.RefundWhenGameCrashed',
    index=0,
    containing_service=None,
    input_type=_REFUNDWHENGAMECRASHEDREQUEST,
    output_type=_REFUNDWHENGAMECRASHEDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMatchDetailByTicketId',
    full_name='ticket.Mobile.GetMatchDetailByTicketId',
    index=1,
    containing_service=None,
    input_type=_GETMATCHDETAILBYTICKETIDREQUEST,
    output_type=_GETMATCHDETAILBYTICKETIDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MOBILE)

DESCRIPTOR.services_by_name['Mobile'] = _MOBILE

# @@protoc_insertion_point(module_scope)
