# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import history_mobile_pb2 as history__mobile__pb2


class MobileStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGameHistory = channel.unary_unary(
                '/history.Mobile/GetGameHistory',
                request_serializer=history__mobile__pb2.GetGameHistoryRequest.SerializeToString,
                response_deserializer=history__mobile__pb2.GetGameHistoryResponse.FromString,
                )


class MobileServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGameHistory(self, request, context):
        """new mobile native grpc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MobileServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGameHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGameHistory,
                    request_deserializer=history__mobile__pb2.GetGameHistoryRequest.FromString,
                    response_serializer=history__mobile__pb2.GetGameHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'history.Mobile', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Mobile(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGameHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/history.Mobile/GetGameHistory',
            history__mobile__pb2.GetGameHistoryRequest.SerializeToString,
            history__mobile__pb2.GetGameHistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class HistoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGameHistoryItems = channel.unary_unary(
                '/history.HistoryService/GetGameHistoryItems',
                request_serializer=history__mobile__pb2.GetGameHistoryItemsRequest.SerializeToString,
                response_deserializer=history__mobile__pb2.GetGameHistoryItemsResponse.FromString,
                )


class HistoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGameHistoryItems(self, request, context):
        """Search history items by type, include ongoing/claims/ended
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HistoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGameHistoryItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGameHistoryItems,
                    request_deserializer=history__mobile__pb2.GetGameHistoryItemsRequest.FromString,
                    response_serializer=history__mobile__pb2.GetGameHistoryItemsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'history.HistoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HistoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGameHistoryItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/history.HistoryService/GetGameHistoryItems',
            history__mobile__pb2.GetGameHistoryItemsRequest.SerializeToString,
            history__mobile__pb2.GetGameHistoryItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
