# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import match_ticket_mobile_pb2 as match__ticket__mobile__pb2


class MobileStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RefundWhenGameCrashed = channel.unary_unary(
                '/ticket.Mobile/RefundWhenGameCrashed',
                request_serializer=match__ticket__mobile__pb2.RefundWhenGameCrashedRequest.SerializeToString,
                response_deserializer=match__ticket__mobile__pb2.RefundWhenGameCrashedResponse.FromString,
                )
        self.GetMatchDetailByTicketId = channel.unary_unary(
                '/ticket.Mobile/GetMatchDetailByTicketId',
                request_serializer=match__ticket__mobile__pb2.GetMatchDetailByTicketIdRequest.SerializeToString,
                response_deserializer=match__ticket__mobile__pb2.GetMatchDetailByTicketIdResponse.FromString,
                )


class MobileServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RefundWhenGameCrashed(self, request, context):
        """called when game crash and backend should be notified and refund ASAP
        only allow ticket status in READY
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMatchDetailByTicketId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MobileServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RefundWhenGameCrashed': grpc.unary_unary_rpc_method_handler(
                    servicer.RefundWhenGameCrashed,
                    request_deserializer=match__ticket__mobile__pb2.RefundWhenGameCrashedRequest.FromString,
                    response_serializer=match__ticket__mobile__pb2.RefundWhenGameCrashedResponse.SerializeToString,
            ),
            'GetMatchDetailByTicketId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMatchDetailByTicketId,
                    request_deserializer=match__ticket__mobile__pb2.GetMatchDetailByTicketIdRequest.FromString,
                    response_serializer=match__ticket__mobile__pb2.GetMatchDetailByTicketIdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ticket.Mobile', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Mobile(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RefundWhenGameCrashed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ticket.Mobile/RefundWhenGameCrashed',
            match__ticket__mobile__pb2.RefundWhenGameCrashedRequest.SerializeToString,
            match__ticket__mobile__pb2.RefundWhenGameCrashedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMatchDetailByTicketId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ticket.Mobile/GetMatchDetailByTicketId',
            match__ticket__mobile__pb2.GetMatchDetailByTicketIdRequest.SerializeToString,
            match__ticket__mobile__pb2.GetMatchDetailByTicketIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
