import unittest
import datetime

import os
from unittest.suite import TestSuite

from Celer_Game.celer_games_api_regression.pythonLib.Celer_account_mobile.account_mobile_run import test_run
from Celer_Game.celer_games_api_regression.pythonLib.Celer_account_mobile import HTMLTestRunner


def all_case():
    case_dir = "/Users/yandong/PycharmProjects/regression/Celer_Game" \
               "/celer_games_api_regression/pythonLib/Celer_account_mobile"
    testcase = unittest.TestSuite()
    discover = unittest.defaultTestLoader.discover(
        case_dir,
        pattern="account_mobile_run.py",
        top_level_dir=None
    )

    testcase.addTests(discover)
    # print(testcase)
    return testcase

# if __name__ == '__main__':
#     suite: TestSuite = unittest.TestSuite()
#     suite.addTests(unittest.TestLoader().loadTestsFromTestCase(test_run()))
#     # suite.addTests(unittest.TestLoader().loadTestsFromTestCase(play_Match_bucket))
#     # 这一步是在当前文件夹里自动生成一个测试报告，测试报告名称就叫：UnittestTextReport.txt.
#     dt = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
#     filename = "/Celer_Game/celer_games_api_regression/common/"
#     with open(filename + dt + 'HTMLReport.html', 'wb') as fp:
#         # with open(dt+'HTMLReport.html', 'wb') as f:
#         runner = HTMLTestRunner.HTMLTestRunner(stream=fp,
#                                                title='Arcade Win Test Report',
#                                                description='generated by HTMLTestRunner.',
#                                                verbosity=2
#                                                )
#         runner.run(suite)


if __name__ == '__main__':
    runner = unittest.TextTestRunner()
    runner.run(all_case())

    dt = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    filename = "/Users/yandong/PycharmProjects/regression/Celer_Game" \
               "/celer_games_api_regression/common"
    with open(filename + dt + 'HTMLReport.html', 'wb') as fp:
        # with open(dt+'HTMLReport.html', 'wb') as f:
        runner = HTMLTestRunner.HTMLTestRunner(stream=fp,
                                               title='Arcade Win Test Report',
                                               description='generated by HTMLTestRunner.',
                                               verbosity=2
                                               )
        runner.run()
